# Generated by Django 3.0.5 on 2021-06-19 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210619_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='titles',
            name='description',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
