# Generated by Django 3.0.5 on 2021-06-19 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_titles_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='titles',
            options={'ordering': ['genre__slug']},
        ),
    ]
