# Generated by Django 3.0.5 on 2021-06-21 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210619_1020'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='titles',
            options={},
        ),
    ]
