# Generated by Django 3.0.5 on 2021-06-29 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='title_id',
        ),
    ]
